domainUrl: "https://georgedavis-tm.github.io"
baseUrl: "/GeorgeDavis-TM"
siteTitle: "Eyedtentee"
siteLogo: "/img/eyedtentee_logo.png"
exclude: ['README.md']
premalink: pretty

# Website Hosting Configuration
# port: 80